In [1]:
import numpy as np
x= np.array([1.5,3.7,2.6,8.3,5.65,9.08,2.2,8.9,1.9,4.7])
def normalize():
    result = (x-min(x))/(max(x)-min(x))
    return result
    

In [3]:
print(x)
y = normalize()

print("after normalization:,")
print(y)

[1.5  3.7  2.6  8.3  5.65 9.08 2.2  8.9  1.9  4.7 ]
after normalization:,
[0.         0.29023747 0.14511873 0.89709763 0.5474934  1.
 0.09234828 0.9762533  0.05277045 0.42216359]


In [5]:
def norm():
    resu = x/max(x)
    return resu
y = norm()

print("after normalization:,")
print(y)

after normalization:,
[0.16519824 0.40748899 0.28634361 0.91409692 0.6222467  1.
 0.24229075 0.98017621 0.2092511  0.51762115]


In [7]:
from sklearn import preprocessing

In [13]:
x1 = np.array([[3,-1.5,2,-5.4],
               [0,4,-0.3,2.1],
               [1,3.3,-1.9,-4.3]])
data_scalar = preprocessing.MinMaxScaler(feature_range=(0,1))
data_2 = data_scalar.fit_transform(x1)
print(x1)
print("after scaling")
print(data_2)

[[ 3.  -1.5  2.  -5.4]
 [ 0.   4.  -0.3  2.1]
 [ 1.   3.3 -1.9 -4.3]]
after scaling
[[1.         0.         1.         0.        ]
 [0.         1.         0.41025641 1.        ]
 [0.33333333 0.87272727 0.         0.14666667]]


In [15]:
data_nor = preprocessing.normalize(x1, norm = 'l1')
print(data_nor)

[[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


In [17]:
# one hot encoding
encoder = preprocessing.OneHotEncoder()
encoder.fit([[0,2,1,12],
            [1,3,5,3],
            [2,3,2,12],
            [1,2,4,3]])
encoded_vector = encoder.transform([[2,3,5,3]]).toarray()
print(encoded_vector)

[[0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]


In [19]:
# label encoding
label_enco = preprocessing.LabelEncoder()
input_cl = ['audi','ford','audi','toyota','ford', 'bmw']

label_enco.fit(input_cl)

for i, item in enumerate(label_enco.classes_):
    print(item, '->', i)

audi -> 0
bmw -> 1
ford -> 2
toyota -> 3
