In [2]:
import torch

# From data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)



In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# With random values
x_random = torch.rand(2, 3)

x_random

tensor([[0.5583, 0.7190, 0.0232],
        [0.2938, 0.4707, 0.8967]])

In [5]:
# With zeros or ones
x_zeros = torch.zeros(2, 2)

x_zeros




tensor([[0., 0.],
        [0., 0.]])

In [6]:
x_ones = torch.ones(2, 2)
x_ones

tensor([[1., 1.],
        [1., 1.]])

In [7]:

# Identity matrix
x_eye = torch.eye(3)

In [8]:
x_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [9]:

# Similar to NumPy's linspace
x_lin = torch.linspace(0, 10, steps=5)
x_lin

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [10]:
# From NumPy
import numpy as np
np_array = np.array([[5, 6], [7, 8]])
x_np = torch.from_numpy(np_array)
x_np

tensor([[5, 6],
        [7, 8]])

In [11]:
print(x_data.shape)     # Dimensions
print(x_data.dtype)     # Data type
print(x_data.device)    # CPU or GPU


torch.Size([2, 2])
torch.int64
cpu


In [12]:
# Tensor operation
# arithm

x = torch.tensor([1, 2])
y = torch.tensor([3, 4])

print(x + y)            # Element-wise addition
print(x * y)            # Element-wise multiplication
print(x @ y)            # Dot product


tensor([4, 6])
tensor([3, 8])
tensor(11)


In [13]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
print(a)
print(b)
c = a @ b               # Matrix multiplication
print(c)

tensor([[0.8448, 0.7282, 0.9202],
        [0.2637, 0.5066, 0.5373]])
tensor([[0.1019, 0.2044, 0.7309, 0.1914],
        [0.7800, 0.5222, 0.3924, 0.1248],
        [0.0381, 0.2590, 0.4807, 0.9308]])
tensor([[0.6892, 0.7912, 1.3456, 1.1091],
        [0.4426, 0.4576, 0.6499, 0.6139]])


In [14]:
x = torch.arange(12)
print(x)
x = x.view(3, 4)        # Reshape to 3x4
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [15]:
x = x.view(4, 3)        # Reshape to 3x4
print(x)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [16]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1, 2])          # Access element
print(x[:, 1])          # Column slice


tensor(6)
tensor([2, 5])


In [ ]:
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# x = torch.rand(2, 2).to(device)


In [ ]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x + 1

y.backward()  # Computes dy/dx
print(x.grad)  # Output: tensor(7.) since dy/dx = 2x + 3 = 7 when x=2


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
