In [1]:
import torch

# From Data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [2]:
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# With random values
x_random = torch.rand(2, 3)
x_random

tensor([[0.3236, 0.9728, 0.2530],
        [0.4113, 0.7738, 0.3744]])

In [4]:
# With zeros or ones
x_zeros = torch.zeros(2, 2)
x_ones = torch.ones(2, 2)

x_zeros

tensor([[0., 0.],
        [0., 0.]])

In [5]:
x_ones

tensor([[1., 1.],
        [1., 1.]])

In [6]:
# Identity matrix
x_eye = torch.eye(3)
x_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [7]:
# similar to numpy's linspace
x_lin = torch.linspace(0, 10, steps = 5)
x_lin

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [8]:
# From numpy
import numpy as np
np_array = np.array([[5, 6], [7, 8]])
x_np = torch.from_numpy(np_array)
x_np

tensor([[5, 6],
        [7, 8]])

In [9]:
print(x_data.shape)
print(x_data.dtype)
print(x_data.device)

torch.Size([2, 2])
torch.int64
cpu


In [10]:
# Tensor Operation
# arithm

x = torch.tensor([1, 2])
y = torch.tensor([3, 4])

print(x + y) # Element wise addition
print(x * y) # Element wise multiplication
print(x @ y) # Dot Product

tensor([4, 6])
tensor([3, 8])
tensor(11)


In [11]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = a @ b
c

tensor([[0.4838, 0.7541, 0.3558, 0.5391],
        [0.7494, 1.1863, 0.5654, 0.8380]])

In [12]:
x = torch.arange(12)
print(x)
x = x.view(3, 4)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [13]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1, 2]) # Access Element
print(x[:, 1]) # Column Slice

tensor(6)
tensor([2, 5])


In [16]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

x = torch.rand(2, 2).to(device)
x

cpu


tensor([[0.5923, 0.7750],
        [0.0347, 0.5787]])