
## What is NumPy?

<img src="numpy-6-step-ml-framework-tools-numpy-highlight.png" alt="a 6 step machine learning framework along will tools you can use for each step" width="700"/>


In [1]:
import numpy as np

### Anatomy of an array

<img src="numpy-anatomy-of-a-numpy-array.png" alt="anatomy of a numpy array"/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimesion (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-deminsional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

In [5]:
import sys
import numpy as np


In [7]:
list_1 = list(range(1000000))
print("list memory:", sys.getsizeof(list_1)+sum(sys.getsizeof(i) for i in list_1))

list memory: 36000056


In [9]:
np_arry = np.arange(1000000)
print("array memory: ", np_arry.nbytes)

array memory:  4000000


# 1. Data types and attributes

In [11]:
a1 = np.array([1,2,3]) # 1D => vector

In [13]:
# shape, dime, dtype, size, type

a1.shape

(3,)

In [15]:
a1.ndim

1

In [17]:
a1.dtype

dtype('int32')

In [19]:
a1.size

3

In [21]:
type(a1)

numpy.ndarray

In [25]:
a2 = np.array([[1,2,3,4],
               [5,6,7,8]]) # 2D arr => matrix

In [27]:
a2.shape,a2.ndim, a2.dtype, a2.size

((2, 4), 2, dtype('int32'), 8)

In [29]:
a2_1 = np.array([[1,2.3,4],
               [5,6,7.8]])
a2_1.shape,a2_1.ndim, a2_1.dtype, a2_1.size

((2, 3), 2, dtype('float64'), 6)

In [31]:
# 3D matrix
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [33]:
a3.shape,a3.ndim, a3.dtype, a3.size

((2, 3, 3), 3, dtype('int32'), 18)

In [39]:
a3_1 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9.1]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [41]:
a3_1.dtype

dtype('float64')

In [43]:
a3_2 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9.1]],
                 [[10,11,12],
                [13,14,15],
                [16,17,18]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])
a3_2.shape

(3, 3, 3)

In [45]:
a = np.array([1,2,3], dtype = np.int8)
a, a.dtype

(array([1, 2, 3], dtype=int8), dtype('int8'))

In [47]:
# int => 8, 16, 32, 64
# uint
# float => 16, 32, 64

i = np.array([2.3,1.5], dtype = np.float16)
i.dtype

dtype('float16')

In [49]:
# int32 => def
# float64 => def

# Creating Array

In [51]:
li = [2,4,6,8]

np.array(li)

array([2, 4, 6, 8])

In [53]:
li_1 = [1,2,3]
li_2 = [4,5,6]
li_3 = [7,8,9]
arr_4 = np.array([li_1,li_2,li_3])
arr_4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
# arange
nu_arr = np.arange(10)
nu_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
nu_arr_1 = np.arange(5,11)
nu_arr_1

array([ 5,  6,  7,  8,  9, 10])

In [59]:
nu_arr_2 = np.arange(5,11,2)
nu_arr_2

array([5, 7, 9])

In [65]:
nu_arr_0 = np.arange(11,22)
nu_arr_0

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [73]:
np.ones(6) # vector => 1D

array([1., 1., 1., 1., 1., 1.])

In [79]:
li_7 = np.ones((6,6)) # 2-D, matrix
li_7

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [81]:
li_7.dtype

dtype('float64')

In [83]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
np.random.rand(2,3)

array([[0.7639161 , 0.81230328, 0.30352885],
       [0.05679197, 0.45517053, 0.77204886]])

In [91]:
np.random.randn(2,3)

array([[ 0.47862709, -0.87476331,  1.66087893],
       [-2.57052842, -1.4285454 ,  1.86278502]])

In [103]:
np.random.randint(2,13,5)

array([ 3,  2,  6, 11, 11])

In [105]:
arr_6 = np.array([45,56,67])
arr_6

array([45, 56, 67])

In [111]:
ze_arr = np.zeros((3,3))
ze_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
a = np.append(ze_arr, [[45, 56, 67]], axis = 0)
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [45., 56., 67.]])

In [117]:
b = np.append(ze_arr, [[45], [56], [67]], axis = 1)
b

array([[ 0.,  0.,  0., 45.],
       [ 0.,  0.,  0., 56.],
       [ 0.,  0.,  0., 67.]])

In [119]:
a = np.append(ze_arr, [arr_6], axis = 0)
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [45., 56., 67.]])

In [123]:
int_ran = np.random.randint(1,11, size = (4,5))
int_ran

array([[ 3,  8,  5,  8,  6],
       [ 9,  5,  7,  6,  3],
       [10, 10,  6,  1,  7],
       [ 4,  4,  6,  8,  3]])

In [125]:
np.delete(int_ran, 1, axis = 0)

array([[ 3,  8,  5,  8,  6],
       [10, 10,  6,  1,  7],
       [ 4,  4,  6,  8,  3]])

In [127]:
int_ran

array([[ 3,  8,  5,  8,  6],
       [ 9,  5,  7,  6,  3],
       [10, 10,  6,  1,  7],
       [ 4,  4,  6,  8,  3]])

In [129]:
np.delete(int_ran, 1, axis = 1)

array([[ 3,  5,  8,  6],
       [ 9,  7,  6,  3],
       [10,  6,  1,  7],
       [ 4,  6,  8,  3]])

In [131]:
f = lambda m,n:n+10*m
A = np.fromfunction(f,(6,6), dtype = int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [133]:
A[2,:]

array([20, 21, 22, 23, 24, 25])

In [135]:
A[:, 4]

array([ 4, 14, 24, 34, 44, 54])

In [137]:
A[3:,:3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [139]:
A[:3,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [141]:
A[3:, 3:]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [143]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [147]:
A[1:5,1:5]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [149]:
# view
B = A[1:5,1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [151]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [153]:
B[:,:] = 0
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [155]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [157]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [159]:
C = B[1:3,1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [161]:
C[:,:] = 17
C

array([[17, 17],
       [17, 17]])

In [163]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])