In [1]:
import numpy as np

In [3]:
# reshaphing and resizing
data = np.array([[1,2],
                 [3,4]])

In [7]:
data.ndim

2

In [9]:
data.shape

(2, 2)

In [11]:
np.reshape(data,(1,4))

array([[1, 2, 3, 4]])

In [13]:
data.reshape(4)

array([1, 2, 3, 4])

In [15]:
data.flatten()

array([1, 2, 3, 4])

In [17]:
data_1 = np.arange(0,5)
data_1

array([0, 1, 2, 3, 4])

In [19]:
col = data_1[:,np.newaxis]
col

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [21]:
row = data_1[np.newaxis,:]
row

array([[0, 1, 2, 3, 4]])

In [23]:
data_1.shape

(5,)

In [25]:
row.shape

(1, 5)

In [27]:
np.vstack((data_1,data_1,data_1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [29]:
np.hstack((data_1,data_1,data_1))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [31]:
np.hstack((col,col,col))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [33]:
data = data_1[:,np.newaxis]
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [35]:
data_1

array([0, 1, 2, 3, 4])

In [37]:
np.hstack((data_1[:,np.newaxis],data_1[:,np.newaxis],data_1[:,np.newaxis]))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [39]:
# sorting
my_arr = np.random.randint(1,20,10)
my_arr

array([ 5,  2, 15,  3, 11, 14,  5,  9,  4, 10])

In [41]:
np.sort(my_arr)

array([ 2,  3,  4,  5,  5,  9, 10, 11, 14, 15])

In [43]:
my_arr_1 = np.random.randint(1,20,size = (3,4))
my_arr_1

array([[15,  4,  5, 19],
       [12, 16, 10,  5],
       [ 4, 12,  8, 15]])

In [45]:
np.sort(my_arr_1)

array([[ 4,  5, 15, 19],
       [ 5, 10, 12, 16],
       [ 4,  8, 12, 15]])

In [47]:
my_arr

array([ 5,  2, 15,  3, 11, 14,  5,  9,  4, 10])

In [51]:
np.flipud(my_arr)

array([10,  4,  9,  5, 14, 11,  3, 15,  2,  5])

In [55]:
np.flipud(np.sort(my_arr))

array([15, 14, 11, 10,  9,  5,  5,  4,  3,  2])

In [57]:
my_arr_1

array([[15,  4,  5, 19],
       [12, 16, 10,  5],
       [ 4, 12,  8, 15]])

In [59]:
np.sort(my_arr_1)

array([[ 4,  5, 15, 19],
       [ 5, 10, 12, 16],
       [ 4,  8, 12, 15]])

In [61]:
np.sort(my_arr_1)[:,::-1]

array([[19, 15,  5,  4],
       [16, 12, 10,  5],
       [15, 12,  8,  4]])

In [63]:
np.sort(my_arr_1,axis = 0)[::-1]

array([[15, 16, 10, 19],
       [12, 12,  8, 15],
       [ 4,  4,  5,  5]])

In [67]:
np.sort(my_arr_1,axis = None)[::-1]

array([19, 16, 15, 15, 12, 12, 10,  8,  5,  5,  4,  4])

In [69]:
my_arr_1

array([[15,  4,  5, 19],
       [12, 16, 10,  5],
       [ 4, 12,  8, 15]])

In [71]:
np.sort(my_arr_1)[::-1,:]

array([[ 4,  8, 12, 15],
       [ 5, 10, 12, 16],
       [ 4,  5, 15, 19]])

In [73]:
np.sort(my_arr_1)

array([[ 4,  5, 15, 19],
       [ 5, 10, 12, 16],
       [ 4,  8, 12, 15]])

In [75]:
my_arr_2 = np.random.randint(1,20,size = (5,4))
my_arr_2

array([[ 4,  9, 13,  5],
       [ 2,  6, 17,  6],
       [16, 15,  8, 13],
       [13, 14, 18, 12],
       [ 4,  5,  5, 15]])

In [77]:
np.sort(my_arr_2)

array([[ 4,  5,  9, 13],
       [ 2,  6,  6, 17],
       [ 8, 13, 15, 16],
       [12, 13, 14, 18],
       [ 4,  5,  5, 15]])

In [79]:
np.sort(my_arr_2)[::-1,:]

array([[ 4,  5,  5, 15],
       [12, 13, 14, 18],
       [ 8, 13, 15, 16],
       [ 2,  6,  6, 17],
       [ 4,  5,  9, 13]])

In [83]:
my_arr_2

array([[ 4,  9, 13,  5],
       [ 2,  6, 17,  6],
       [16, 15,  8, 13],
       [13, 14, 18, 12],
       [ 4,  5,  5, 15]])

In [81]:
np.sort(my_arr_2,axis = 1)[::-1]

array([[ 4,  5,  5, 15],
       [12, 13, 14, 18],
       [ 8, 13, 15, 16],
       [ 2,  6,  6, 17],
       [ 4,  5,  9, 13]])

In [85]:
np.flipud(np.sort(my_arr_2))

array([[ 4,  5,  5, 15],
       [12, 13, 14, 18],
       [ 8, 13, 15, 16],
       [ 2,  6,  6, 17],
       [ 4,  5,  9, 13]])

In [87]:
ar1 = np.array([12,23,34])
ar2 = np.array([34,45,56])
ar1+ar2

array([46, 68, 90])

In [89]:
ar_1 = np.array([[1,2,3],
                 [4,5,6]])
ar_2 = np.array([[1,2,3],
                 [4,5,6]])
ar_1+ar_2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [91]:
ar1*ar2

array([ 408, 1035, 1904])

In [93]:
ar_1*ar_2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [95]:
# broadcasting numpy
mya1 = np.array([14,15,16])
mya2 = np.array([10])

In [97]:
mya1

array([14, 15, 16])

In [107]:
mya1.shape

(3,)

In [99]:
mya2

array([10])

In [109]:
mya2.shape

(1,)

In [101]:
mya1+mya2

array([24, 25, 26])

In [103]:
mya3 = np.random.randint(1,20, size = (3,4))
mya3


array([[15, 14, 18, 14],
       [ 3, 16, 13, 12],
       [19,  5, 15, 12]])

In [105]:
mya1*mya3

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [111]:
mya1[np.newaxis,:] * mya3


ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

In [113]:
mya1[np.newaxis,:]

array([[14, 15, 16]])

In [115]:
# 1=> scalar
arr = np.array([1,2,3])
res = arr+1
res

array([2, 3, 4])

In [117]:
# 1D / 2D
arr

array([1, 2, 3])

In [119]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
arr+arr2

array([[2, 4, 6],
       [5, 7, 9]])

In [121]:
arr*arr2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [123]:
A1 = np.random.randint(1,20,size = (3,4))
A1

array([[ 3,  8, 16, 11],
       [19,  4,  8, 17],
       [ 9,  1, 14,  8]])

In [125]:
A2 = np.array([[5],[6],[7]])
A2

array([[5],
       [6],
       [7]])

In [127]:
A1*A2

array([[ 15,  40,  80,  55],
       [114,  24,  48, 102],
       [ 63,   7,  98,  56]])

In [129]:
# copying
a1 = np.array([10,12,14,16,18,20])
a1

array([10, 12, 14, 16, 18, 20])

In [131]:
a2 = a1.copy()
a2

array([10, 12, 14, 16, 18, 20])

In [133]:
a2[1] = 78
a2

array([10, 78, 14, 16, 18, 20])

In [135]:
a1

array([10, 12, 14, 16, 18, 20])

In [137]:
a3 = a1.view()
a3

array([10, 12, 14, 16, 18, 20])

In [139]:
a3[3] = 98
a3

array([10, 12, 14, 98, 18, 20])

In [141]:
a1

array([10, 12, 14, 98, 18, 20])

In [143]:
f = lambda m,n:n+10*m
A = np.fromfunction(f,(6,6), dtype = int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [147]:
B = A.view()
B

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])